ConfigVersion: "1.13" # DO NOT CHANGE THIS
# -------------------------------------------------------------------------------------------------- #
#                                                                                                    #
#                                       LoginTo Configuration                                        #
#                                                                                                    #
# -------------------------------------------------------------------------------------------------- #


commands-settings:
  # Enter here the commands that will be allowed before logging in (the /login, /register, and /changepassword commands will always be active; aliases like /l and /r must be added below)
  pre-login-allowed-commands:
    - "l"
    - "r"

auth-security:

  # Kick the player if they enter an incorrect password during /login?
  kick-on-invalid-password: true
  # Maximum login attempts allowed before getting kicked
  max-login-attempts: 3

  # Kick players who remain unauthenticated for too long?
  kick-on-auth-timeout: true
  # Seconds allowed to authenticate before the kick occurs
  auth-timeout-seconds: 10

password-requirements:
  # Require specific special characters in the password during registration?
  require-special-chars: false
  # List the required characters if the setting above is set to true
  required-char-list: ''

  # Define password length constraints
  length-check:
    enabled: true
    min-length: 8
    max-length: 32

  # Settings for too common passwords
  banned-password:
    # Decline any loginto action if the password is too simple
    decline-on-common-password: true

      # Use the RockYou password list (if this is enabled, the plugin will download the txt file from this link: https://weakpass.com/download/90/rockyou.txt.gz)
    # That file uncompressed will be around 130MB
    use-rockyou: true

      # If you want to add some banned password, put them here
    # The placeholder '%username%' is to define the player name
    banned-password:
      - "%username%"

otp-config:

  # Set here the server name that the player will see in the authentication app for the code.
  # Note: This is not the Bungee/Velocity server name, but the public server name (e.g., Hypixel or Mineman).
  # Use only URL-friendly characters
  server-name: "MyServer"


# World and teleportation
spawn-settings:
  # Enable automatic teleportation to a specific location upon joining?
  teleport-on-join: false
  
  # Target dimension for the teleport (e.g., world, world_nether, world_the_end)
  target-dimension: 'world'
  
  # Exact coordinates for the teleportation point
  spawn-coordinates:
    x: 0
    y: -64
    z: 0

  # Return the player to their last known location after a successful login?
  restore-previous-location: true


# Integrations and webhooks
integrations:

  proxy:
    # Specify the server where players should be sent after logging into your network (e.g., 'lobby-1'). 
    # If you are not using a proxy or wish to disable this feature, leave this field empty.
    server-post-login: ""

  discord:
    # Webhook URLs and custom messages (Supports Discord Markdown)
    # Available variables: %playerName%, %targetPlayer%
    
    register-webhook-url: ''
    register-message: "**%playerName%** has completed the registration"

    login-webhook-url: ''
    login-message: "**%playerName%** has logged in"
    
    unregister-webhook-url: ''
    unregister-message: "**%playerName%** has deleted **%targetPlayer%**'s account"

    password-change-webhook-url: ''
    password-change-message: "**%playerName%** has changed their password"


# Storage
storage:

  # Supported storage methods: sqlite, mysql, postgre, h2
  # Changing this option requires a full server reboot
  storage-type: "sqlite"

  database:
    # Connection details for the database (for sqlite or h2, you will only need to change the name)
    host: "localhost"
    port: 3306
    name: "LoginTo_DB"
    user: ""
    password: ""


# Premium system (Original accounts)
premium:
  # Enables AutoLogin, /premium, and /cracked commands.
  # Requirements: the server must be in offline mode and NOT in a network (not linked to a proxy)
  #
  # When the user joins the server, if the username is premium (for example 'Dream'), the server will perform the normal
  # mojang's authentication. If the player is from floodgate, the plugin will let him pass since it's verified by
  # floodgate. If the username is not premium (like a random name), the server will let that player pass without mojang's
  # authentication, but the plugin will still require the /login command from the player
  enable-premium-features: true

  # The duration of the name cache (in hours).
  # After X hours, the player's record will expire and the plugin will remove it.
  # The cache.db file can be deleted when the server is off
  cache-duration: 24

  # When premium authentication is enabled, premium and Bedrock players typically must use /register during their first login.
  # This feature automates that process by generating a random password, allowing them to bypass registration entirely.
  auto-register: true

  # A list of players name that will not get affected by the premium authentication security even if their name is premium
  # Even if those player will still be able to access the server, they will still need to do /login <password> before playing
  bypass-premium-check-for-players: []


logging:
  # This feature logs all players who join the server
  logging: true

  # The date and time format for displaying logs
  # DO NOT use spaces " " within the time format. You can use "HH:mm:ss-dd/MM/yyyy", but NOT "HH mm ss dd MM yyyy".
  # If you wish to use spaces, instruct your staff to use only the /getlogs <user> command without specifying the day.
  # Note: If you use the /getlogs command with the time selector, the date format must strictly remain "dd/MM/yyyy".
  date-format: "HH:mm:ss dd/MM/yyyy"



plugin-utility:
  # Check for new updates on startup and notify the console?
  enable-update-checker: true
  
  # Show the 'Service offered by LoginTo' watermark? If you want to support my work, please consider leaving this enabled.
  show-watermark: true

  # If set to false, the plugin will require PacketEvents to be installed as a separate plugin on the server.
  # If set to true, the plugin will use the built-in PacketEvents API.
  # Disclaimer: If possible, I recommend setting this to 'false' and installing the dedicated PacketEvents plugin. 
  # Doing so helps prevent any internal compatibility issues regarding PacketEvents within this plugin.
  use-built-in-packetevents-api: true

  # If this setting is on, LoginTo will generate the experimental.yml file that will contain every feature under development
  # Those features might be unstable until their full release
  # (In order for this file to be generated, a reload or restart is needed)
  enable-experimental-features: false


